import 'bootstrap/dist/css/bootstrap.min.css'
import '../public/css/layouts/admin/header.css'
import '../public/css/layouts/admin/left-sidebar.scss'
import '../public/css/globals.css'
import 'react-toastify/dist/ReactToastify.css'
import '../public/css/layouts/user/header.css'
import '../public/css/layouts/user/footer.css'
import '../public/css/layouts/user/home/home.css'
import '../public/css/layouts/user/home/section-hero.css'
import '../public/css/layouts/user/home/section-featured-cities.css'
import '../public/css/layouts/user/home/section-our-features.css'
import '../public/css/layouts/user/home/section-home-blogs.css'
import '../public/css/layouts/user/loader/full-page-loader.css'
import '../public/css/signup.css'
import '../public/css/login.css'
import '../public/css/layouts/user/me/me.css'
import '../public/css/layouts/user/me/sidebar.css'
import '../public/css/layouts/user/me/me-tab.css'
import '../public/css/layouts/user/stay-card.css'
import '../public/css/layouts/user/popup/popup-details.css'
import '../public/css/layouts/user/popup/popup-image.css'
import '../public/css/layouts/user/city-card.css'
import '../public/css/layouts/user/blog-card.css'
import '../public/css/layouts/user/home/list-hotels-demo.css'
import '../public/css/layouts/user/hotel-details/hotel-models.css'
import '../public/css/layouts/user/hotel-details/hotel-details-header.css'
import '../public/css/layouts/user/hotel-details/hotel-details-main.css'
import '../public/css/layouts/user/hotel-details/hotel-details-calendar.css'
import '../public/css/layouts/user/hotel-details/hotel-details-maps.css'
import '../public/css/layouts/user/hotel-details/hotel-details-sidebar.css'
import '../public/css/layouts/user/hotel-details/room-picker-item.css'
import 'react-calendar/dist/Calendar.css'
import 'react-datepicker/dist/react-datepicker.css'
import 'swiper/css'
import 'swiper/css/pagination'
import '../public/css/layouts/admin/profile-admin.scss'
import '../public/css/layouts/admin/manage-user.scss'
import '../public/css/layouts/user/checkout.css'
import '../public/css/layouts/user/paydone.css'
import '../public/css/layouts/user/home-contact.css'
import '../public/css/layouts/user/contact.scss'
import '../public/css/layouts/user/about.scss'
import '../public/css/layouts/user/blogs.scss'
import '../public/css/layouts/user/blog-card.scss'
import '../public/css/layouts/admin/manage-hotels.scss'
import '../public/css/layouts/user/me/booking-history/index.css'

export default function MyApp ({ Component, pageProps }) {
  // Use the layout defined at the page level, if available
  const getLayout = Component.getLayout || ((page) => page)

  return getLayout(<Component {...pageProps} />)
}
